# :\u8BBE\u7F6E\u7AEF\u53E3\u53F7
server:
  port: 8086
  servlet:
    context-path:
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
  session:
    store-type: redis
  jackson:
    serialization:
      indent_output: true
mybatis:
  type-aliases-package: com.top.yirenbao.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.newer.hospital.mapper: debug #\u8F93\u51FAdebug\u7EA7\u522B\u53CA\u4EE5\u4E0A\u7EA7\u522B\u7684\u65E5\u5FD7
    org.springframework.security: info
jwt:
  secret: mySecret   #\u81EA\u5B9A\u4E49\u79C1\u94A5\u540D\u79F0
  expiration: 99999  #token\u8FC7\u671F\u65F6\u95F4  s
  header: Authorization  #\u5B9A\u4E49\u8BF7\u6C42\u5934\u90E8\u4E2D\u7684\u81EA\u5B9A\u4E49\u5C5E\u6027\u540D\u79F0
  tokenHead: Bearer #\u627F\u63A5\u5B57\u7B26\u4E32
  path: /auth  #controller\u4E2D\u8BF7\u6C42\u8DEF\u5F84 \u767B\u5F55
  refresh: /refresh  #controller\u4E2D\u8BF7\u6C42\u8DEF\u5F84 \u5237\u65B0


  # :\u65E5\u5FD7
#logging:
#  level:
#    root: info
#    org.springframework.web: debug
#  file: d:/log/my.log
